services:
  web:
    build: .
    container_name: excaliber-web
    env_file:
      - server/.env
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
